= Immortals
Mathieu Glachant <syvwlch@gmail.com>
:toc:

== The Issue with Immortal Sapients

=== Lifespans of Immortal Sapients

Fantasy settings often have at least one species of immortal sapients, e.g. Tolkien's Elves. Individuals can be killed thru violence or accident, but do not suffer from disease or die from old age.

Lifespans routinely span centuries, and can span millennia. Galadriel, for example, is 7,000 years old by the end of the Third Age, and first generation elves (Cirdan, possibly?) would be well over 11,000 years old.

=== Timescales of Language Evolution

These lifespans are on the timescales of the evolution of entire families of languages. Proto-Indo-European is 4,500 to 5,000 years old. Semitic languages last shared a common ancestor 7,000 years ago, and seem to have split off from Kushitic languages 8,000 years ago.

A Galadriel in the Fertile Crescent would have personal memories of the Indo-European noun case system evolving, and then disappearing in many of the daughter languages; if she wanted to know how the Semitic triconsonant root system arose, she could get a firsthand account from others a little older than she.

Languages are a good yardstick for the sheer amount of change that can happen over such timescales, because they provide granularity down to much shorter lengths. Readers grapple with this when meeting non-contemporary texts. After only a few decades, the language sounds quaint and antiquated. After a handful of centuries, comprehension is a struggle. After one millennium, one faces a different language altogether.

=== Timescales of Evolution of Agriculture

Agriculture is another field of mortal endeavor with 10,000 years of history. Neolithic crop domestication (wheat, barley, peas, lentils, etc...) is 11,500 years old in the Fertile Crescent. Rice domestication in China is 8,000 years old. Pigs were domesticated 13,000 years ago, cattle and sheep by 11,000 years ago. All of which have seen refinements and changes to the present day, see modern short-wheats for example.

=== Why Is This a Problem?

All of this to point out: these immortal sapients are presented as having stable, often small-c conservative cultures, despite a lived experience of contact with mortal societies that are undergoing sustained patterns of change. I do not think this is realistic.

One possible reaction to mortal neighbors who invent entire new languages while you're away on your honeymoon, and who go from hunting & gathering to intensive agriculture while you're still pondering where to buy your vacation home is, perhaps, a reactionary denial. However that would put you at a steep disadvantage with the mayflies who keep coming up with a better way to feed and equip their armies, and oh, look at that, they just invented navies. What will they think of next? Powered flight?

Just as likely, and probably much more adaptive, would be to embrace all that change. 7,000 years of active learning, an innate ability to take the long view married to a willingness to run experiments for centuries.

== Forever Young at Heart

What would a functionally immortal sapient who embraces change be like?

=== Delight in languages

Elves are often portrayed as delighting in language. They sing, they recite poetry at the drop of a hat, and fawn over old hobbits who translate it or write it in new styles they've never heard before. There's even a sense in which what mortals call a 'spell' is simply elven spoken-word sub-creation so intense the world responds to it.

Tolkien's elves are able to evolve multiple languages while first generation elves are still around, without much linguistic tension, so at least initially they do not exhibit conservative tendencies here. Before they even meet any mortals, this flexibility seems to ossify once Sindarin and Quenya are established.

I find that odd.

Perhaps those elves who made it to Valinor and saw the light of the Trees before the kinslaying and the exile to Middle-Earth are more keenly aware of the fallen nature of the world. Once established in Beleriand, their own marred nature is reflected in this conservative urge towards a lost golden age which ultimately leads to Galadriel shielding one forest from the ravages of time until it is time to fade into the West.

Absent this trauma, I believe immortal sapients would keep their love of new languages, new poetic forms, and new songs. I believe they would embrace the quicksilver evolution of mortal languages, the meteoric flare of a Shakespeare, Virgil, or Dante stretching the sinews of one mayfly tongue to their utter limit. How could they resist learning English, Latin, or Italian with such rewards for their labor?

Why would they not compose great epics of alliterative verse in languages best suited to that form, and sonnets in others, and alexandrine verse in yet others? Once the mortals invent opera, why would the immortals refuse to hear it? Once an Eminem is weaving patterns never heard on any tongue, mortal or otherwise, why would they not line up to challenge him to a rap battle?
