= Immortals
Mathieu Glachant <syvwlch@gmail.com>
:toc:

== The Issue with Immortal Sapients

=== Lifespans of Immortal Sapients

Fantasy settings often have at least one species of immortal sapients, e.g. Tolkien's Elves. Individuals can be killed thru violence or accident, but do not suffer from disease or die from old age.

Lifespans routinely span centuries, and can span millennia. Galadriel, for example, is 7,000 years old by the end of the Third Age, and first generation elves (Cirdan, possibly?) would be well over 11,000 years old.

=== Timescales of Language Evolution

These lifespans are on the timescales of the evolution of entire families of languages. Proto-Indo-European is 4,500 to 5,000 years old. Semitic languages last shared a common ancestor 7,000 years ago, and seem to have split off from Kushitic languages 8,000 years ago.

A Galadriel born in the right place could have personal memories of the Indo-European noun case system evolving, and then disappearing in many of the daughter languages; if she wanted to know how the Semitic triconsonant root system arose, she could get a firsthand account from others a little older than she.

Languages are a good yardstick for the sheer amount of change that can happen over such timescales, because they provide granularity down to much shorter lengths. Readers grapple with this when meeting non-contemporary texts. After only a few decades, the language sounds quaint and antiquated. After a handful of centuries, comprehension is a struggle. After one millennium, one faces a different language altogether.

=== Timescales of Evolution of Agriculture

Agriculture is another field of mortal endeavor with 10,000 years of history. Neolithic crop domestication (wheat, barley, peas, lentils, etc...) is 11,500 years old in the Fertile Crescent. Rice domestication in China is 8,000 years old. Pigs were domesticated 13,000 years ago, cattle and sheep by 11,000 years ago. All of which have seen refinements and changes to the present day, see modern short-stalked wheats for example.

=== Why Is This a Problem?

All of this to point out: these immortal sapients are presented as having stable, often small-c conservative cultures, despite a lived experience of contact with mortal societies that are undergoing sustained patterns of change. I do not think this is realistic.

One possible reaction to mortal neighbors who invent entire new languages while you're away on your honeymoon, and who go from hunting & gathering to intensive agriculture while you're still pondering where to buy your vacation home is, perhaps, a reactionary denial. However that would put you at a steep disadvantage with the mayflies who keep coming up with a better way to feed and equip their armies, and oh, look at that, they just invented navies. What will they think of next? Powered flight?

Just as likely, and probably much more adaptive, would be to embrace all that change. 7,000 years of active learning, an innate ability to take the long view married to a willingness to run experiments for centuries.

== Forever Young at Heart

What would a functionally immortal sapient who embraces change be like?

=== Delight in languages

Elves are often portrayed as delighting in language. They sing, they recite poetry at the drop of a hat, and fawn over old hobbits who translate it or write it in new styles they've never heard before. There's even a sense in which what mortals call a 'spell' is simply elven spoken-word sub-creation so intense the world responds to it.

Tolkien's elves evolve multiple languages in the presence of first generation elves without much linguistic tension, so at least initially they do not exhibit conservative tendencies here. Before they even meet any mortals, however, this flexibility seems to ossify once Sindarin and Quenya are established.

I find that odd.

Perhaps those elves who made it to Valinor and saw the light of the Trees before the kinslaying and the exile to Middle-Earth are more keenly aware of the fallen nature of the world. Once established in Beleriand, their own marred nature is reflected in this conservative urge towards a lost golden age which ultimately leads to Galadriel shielding one forest from the ravages of time until it is time to fade into the West.

Absent this trauma, I believe immortal sapients would keep their love of new languages, new poetic forms, and new songs. I believe they would embrace the quicksilver evolution of mortal languages, the meteoric flare of a Shakespeare, Virgil, or Dante stretching the sinews of one mayfly tongue to their utter limit. How could they resist learning English, Latin, or Italian with such rewards for their labor?

Why would they not compose great epics of alliterative verse in languages best suited to that form, and sonnets in others, and alexandrine verse in yet others? Once the mortals invent opera, why would the immortals refuse to hear it? Once an Eminem is weaving patterns never heard on any tongue, mortal or otherwise, why would they not line up to challenge him to a rap battle?

=== Immortal Hobbies with Mortal Languages

Given immortal sapients who love the languages of mortals, what shenanigans might they get up to?

They might influence the evolution of mortal languages in certain directions, almost like a form of gardening. Techniques could range from introducing neologisms and slang, to establishing the gold standards which 'set' a language, like Cicero for Latin, Dante for Italian, or Homer for Greek.

Alternatively, they could invent entire constructed languages (conlangs) which did _not_ have living, mortal speakers, and leave a body of work in those languages for later mortals to find... or they might set up small groups of mortals speaking languages completely unrelated to any of their neighbors.

=== Raising Young

In mortal families, the young tend to be neophilic, and inclined to challenge the established traditions of their elders, who in turn tend to be more conservative. This stems from a balance to be struck between curiosity, which promotes learning, and risk-avoidance, which becomes more important as older individuals have more to lose for themselves and their dependents.

However, as we saw above, immortals risk a lot more - in the long term - by being set in their ways, as they lose the ability to adapt to external pressures from the environment and from the competition of mortals.

In immortal families where the elders never stop learning, and never stop embracing change, would there come a time when the young, having learned a first coherent-but-ephemeral set of cultural traditions, would reject their elders' embrace of the next new thing? Immortal youth might rebel, but in a conservative reaction to their elders' latest fad or craze, at least until the time comes to set aside childish things.

Perhaps, in such a world, mortals could evolve from the immortals thru neoteny, never growing past this conservative phase... and coming to reproduce without reaching adulthood.

=== Knowledge and Skills

How many mortal lifetimes does an immortal have to live, actively seeking new knowledge and experiences, before they have the skills to fend for themselves in almost any environment? When you are older than agriculture itself, and have lived thru the rise and fall of several urban empires, what crisis could befall you which you would not know how to face?

Would a society of immortals experience wealth and power accumulation in the hands of the few, or would time and the ability to always walk away to a fresh start somewhere else make that impossible?

I tend to think that such a society would reach a form of thermal equilibrium with respect to the ability to command the resources for food, energy, raw materials, or even labor... while the complexity of relationships between individuals and groups continued to grow well after no material difference was in evidence. After all, if an immortal found themselves without resources, they have the skills to recoup their losses, even if that takes a few decades.

In other words, I would expect immortals to effectively live in a post-scarcity condition, because they are ALWAYS time-rich. That, combined with millennia of experience and knowledge and luck-favoring-the-prepared, would ensure it. Such a condition would not, I think, lead to a uniform, stagnant society, but instead leave immortals free to pursue various interests, form alliances of ornate complexity dedicated to pursuits shared with arbitrarily small numbers of peers, and otherwise spin such a tangled web of relationships to present a forbidding challenge to a new entrant or to someone wishing to break free of it.

All the more reason for the young to balk at diving into the deep end.

== The Social Black Hole

An immortal society in which any temporary material disparity in wealth or power is very quickly spread out amongst all, but in which the social, cultural, artistic, and moral ties between individuals continue to grow more and more complicated and tangled, is basically like a social black hole.

=== Analogy with Spacetime Black Holes

One of the current interpretation of black holes is that they are systems which reach thermal equilibrium very quickly relative to the time during which their complexity continues to grow. Where thermal equilibrium means the distribution of energy is very uniform, and complexity means the number of connections each individual part makes with all the other parts.

Once an individual falls past the event horizon, a certain threshold of proximity and interaction with the core of the black hole, this societal complexity is growing around them at such a rate that they cannot swim upstream fast enough to escape. In concrete terms, an immortal deep inside a culture of fellow 10,000 year old nerds may no longer be able to function outside that tight self-referential knot of in-jokes, purpose-built-languages, and social obligations.

Only an enduring passion for the surprises and delights of mortal cultures might cause an immortal to break free, and form of sort of Hawking radiation detectable from outside the event horizon... or perhaps they are still free because no concentration of immortals has yet reached the threshold density to create a social black hole?

In the analogy with a black hole, the main way the object interacts with the rest of the universe is via gravity, which can be felt at a distance past the event horizon. What would be equivalent of gravity, in a social black hole that holds a massive amount of sapient lived experience, memories, and knowledge which can never escape its own proximity?

It would have to be an idea, or a related system of ideas, without which it is impossible to conceive of, or talk about, what is going on inside the social black hole, but with which an entire new functionally infinite space of idea is exploding into existence.

=== Idea Singularities

In a sense, a Social Black Hole does not require physical proximity. It exists in idea-space, and can be thought of as such a concentration of coherent, adjacent ideas that it bends idea-space itself until the gradient gets so steep all minds wandering too close can never escape again.

In a sense, the conceptual space inside this event horizon grows faster than any mind can communicate, giving rise to an area in idea-space which has a finite surface which can be approached and circumscribed, but an infinite, forever-growing internal volume.

Minds inside such an idea singularity would still be able to move about the physical world, but communication of new ideas with other minds would be one way, outside-in. Primarily because no mind could think fast enough to translate an internal thought into external ideas.

Fundamentally, such a Social Black Hole can only be understood and discussed from the inside, but once inside a mind cannot never truly escape it, as it becomes impossible to discuss anything at all without reference to ideas from inside.

In a sense the vocabulary required to describe the inside of an idea singularity is growing faster than someone external could possibly be exposed to it, let alone learn it. An attempt to communicate from the inside-out would sounds like gibberish.

=== Decay of an Idea Singularity

There's nothing inherent to immortals that makes them more likely than mortals to form these idea singularities, except that the underlying dense web of conceptual relationships are not brought to an end by the death of the participants. So in a sense, these would be like a religion, or a philosophical school, or an art movement, that never ended but instead became more and more syncretic and baroque.

Amongst mortals the turnover of generations means that even if an idea singularity does form, like say during a revolution, it tends to decay. Escape is always possible via death. The conservatism of adult mortals would also make the idea singularity sclerotic, unable to absorb and distribute new ideas or external influences, leading to instability and fission. Lastly, the disdain of the mortal youth for their elders' quaint ideas would repel them, making it difficult to replace the aging members with fresh minds.

Amongst immortals, these natural decay pathways are blocked, short of a massive die-off. This makes these idea singularities much more of a threat particularly to conservative youth who would fear that irreversible conceptual fall.
