= The Lacy Veil
Mathieu Glachant <syvwlch@gmail.com>
:toc:

== A Room of One's Own

It wasn't much of a room, if one were honest. Later, Kea would smile fondly as she reminisced about her 'book-cupboard', intent on evoking in her audience a true impression of its size and purpose -- yet at the time nothing made her feel bigger inside than closing its door on the noise of her family downstairs.

She hadn't stood to inherit the little study so soon, but her brother hadn't followed in their eldest sister's footsteps. Instead of years of study and a life of devotion to one of the Useful Gods, he'd joined the Guard as soon as they'd have him.

Mother had grumbled about filial ingratitude but not even she could claim surprise. Instead, as often happened when Gil proved a disappointment, she'd picked up the threads of her familial ambitions with the next child in line.

Kea was too young for the open temple classes, and while the family was not quite in the means for a tutor, by the same token it could ill afford an idle child and a useless room.

With a firmer grasp of domestic economy than of pedagogy, Mother had decreed that the sister already in temple service could serve just as well to guide her young successor on the first steps to the same destination. By post if that was all her existing duties allowed.

So while it wasn't much of a room, if Kea were honest to her younger self it was a place of boundless freedom and potential. Safely ensconced within the demanding and blind faith of Mother, but under the benign and distracted tutelage of her absent sister.
