= The Lacy Veil
Mathieu Glachant <syvwlch@gmail.com>
:toc:

== A Room of One's Own

It wasn't much of a room, if one were honest. Later, Kea would smile fondly as she reminisced about her 'book-cupboard', intent on evoking in her audience a true impression of its size and purpose -- yet at the time nothing made her feel bigger inside than closing its door on the noise of her family downstairs.

She hadn't stood to inherit the little study so soon, but her brother hadn't followed in their eldest sister's footsteps. Instead of years of study and a life of devotion to one of the Useful Gods, he'd joined the Guard as soon as they'd have him.

Mother had grumbled about filial ingratitude but not even she could claim surprise. Instead, as often happened when Gil proved a disappointment, she'd picked up the threads of her familial ambitions with the next child in line.

Kea was too young for the open temple classes, and while the family was not quite in the means for a tutor, by the same token it could ill afford an idle child and a useless room.

With a firmer grasp of domestic economy than of pedagogy, Mother had decreed that the sister already in temple service could serve just as well to guide her young successor on the first steps to the same destination. By post if that was all her existing duties allowed.

So while it wasn't much of a room, if Kea were honest to her younger self it was a place of boundless freedom and potential. Safely ensconced within the demanding and blind faith of Mother, but under the benign and distracted tutelage of her absent sister.

== In The Hands of a Child

Sister's syllabus gave pride of place to theory and catechism, perforce. Great strides have since been made in teaching the practical applications of piety at a remove, but doubtless even the greatest teachers of the day would have judged the task difficult and dangerous. She does not seem to have even considered the attempt.

Kea, as the recipient of this instruction, did not much mind the form it took -- that of a variety of reading assignments culled from the small library in her inherited study, accompanied by a few perfunctory questions aimed to confirm their perusal -- but often found its content rather dry: divine dynasties, saintly orders of succession, or the proper and pious propitiation of those of the Gods who could be convinced to be Useful.

She quickly realized that if her sister never gave her more than a day or two's reading per week, it had to be so she could pursue her own course thru the other books, carefully avoiding anything that looked like it might be the object of a future assignment. Out of respect for her sister's lesson plan, the careful order of which had to have its own reason, of course.

By this method of elimination, Kea found herself with days of blissful solitary attention to lavish on a single book. A shabby little thing, with a faded if once brightly colored cover, she found tucked behind its more stodgy brethren.

'The Handiwork of Thine Hands', its cracked spine proclaimed, and the elaborate title page contained a dedication to Eivy, Our Lady of Surprises -- a minor deity of limited Utility whom Kea vaguely associated with children's puzzles and games, and which she did not recall reading about in her sister's lessons.

The pages of the Handiwork held dozens of poorly drawn diagrams showing a progression of cat's cradle patterns, many with fanciful names and every margin filled with a dense thicket of hand written notes.

She couldn't make heads or tails of it.

She couldn't have been happier.

== The Lacy Veil

Progress with the Handiwork was anything but regular. In fact, there didn't seem to be much progress at all for the longest time. The hardest part turned out to be understanding what the book was about. She knew early on, as she tried the patterns, that it wasn't simply about cat's cradle.

Many of the early patterns weren't particularly interesting to look at, and often differed by the tiniest of nuances, of which the book seemed to make more than was warranted. As these were the only patterns the book actually gave step by step diagrams for, they were all she could practice for a while.

The more complex diagrams had her stumped for a long time. In the end, she took the simplest one and cheated -- arranging the strings loops and folds just so on the floor before sliding it gingerly on her fingers.

From there, she tried to work backwards. The first few steps to undue the pattern were obvious, but soon she couldn't be sure what to do next... except something felt familiar. Moving forward again, she rebuilt the last few steps of the pattern. Backwards, forwards, aha!

These were the last few steps of one of the basic patterns. Her hands shaking a little, she tried to undo that pattern from memory, but got snarled up before she was done.

Yet she knew. She knew she had it; the pattern had been coming undone in a way that felt right. She just needed to know the basic patterns backwards and forwards.

It took the rest of the day, but eventually she figured out that this pattern was the simple combination, back to back, of two of the basic patterns.

She hadn't know the world, or her head, could hold such wondrous ideas in it.

The pattern was called the Lacy Veil.

== Yellow World

Figuring out the other advanced patterns would have taken a long time, except Kea noticed after the fact that the handwritten notes assigned each basic pattern a shorthand sign, and listed the ones required to create each pattern.

A little experimentation soon revealed that the author of the notes used other signs to represent various ways of combining basic patterns, some of which were obvious and others less so, and the lists in the margins quickly became as cryptic, if not more so, than the diagrams they accompanied.

With their help, however, she was soon able to recreate every diagram in the book, and to her delight discovered that the last one held a surprise, as befitted a set of puzzles dedicated to Our Lady of Puzzles.

Upon completing the last pattern, which the Handiwork called Yellow World, the string burst into heatless flame, hanging in mid-air and filling her little study with a golden light -- even after she yanked her hands back in alarm.

She savored the moment, the many hours of work, the joys of discovery and the setbacks overcome had led to this, and she was grateful for the unnamed author of this book, who had crafted this pattern in her soul as surely as her hands had created the knot of light fading slowly before her brimming eyes.

== Call Eivy

In the wan light of the study's small window, as it dawned on her that Eivy had consented to be of Use thru her, an unconsecrated child, and without any of the costly and elaborate sacrifices her sister's lessons assured her were necessary for the slightest applications of Piety, it never occurred to Kea to doubt herself or the work of her hands.

No, she believed in the Handiwork, and she chose to doubt all those other books instead. She still had so much to learn from the handwritten notes that filled its precious pages, with hints of other patterns for which there were no diagrams, just cramped shorthand and cryptic asides about an infinite array of patterns, more than could be counted, enough to fill all the books in all the libraries of all the temples of the world, without capturing a single one of any Use... unless Eivy deigned to help?

The note writer thought she might be enticed. Was she not Our Lady of Puzzles? Did she not delight in secrets, keeping them hidden, and bringing them to light, for their own sake and for nothing else?

Yes, here in the margins of the Lacy Veil pattern, some thoughts on how to twist it into another pattern to Call Eivy, to ask her to be of Use compiling a new library of secrets, books upon books of patterns, patterns of Utility without Piety.

A library to steal the power of the gods.

No, a library to steal the power of our own handiwork back from the thieving gods.
