= Living with Immortality
Mathieu Glachant <syvwlch@gmail.com>
:toc:

== Prologue

This is the bit I'm really bad at.

I was there, I saw it happen, and with enough wine in me, I can tell the story well enough. Enough to make you laugh at our folly, with enough wine in you. Sober, I can whisper the same story to heavy-lidded children fighting against sleep, and mostly they will dream of courage and treasure. Mostly.

So yes, back home I'm a teller of tales... for people I've known their entire lives, and who've heard my tales exactly that long. If I get a little lost, they all know how these stories go, and are not slow to remind me.

You, however... Children of children of strangers, posterity, how shall I address you? What do we share, you and I, which I can build this story on, that we might meet in the middle?

Have you stood in the surf, the sand sweeping over your toes and the foam splashing your shins? Can I start there, and assume you will know that much?

Have you given birth, suckled a child? Have you sailed at night towards the lights of a sleepy port rich for the plunder? Have you buried husbands?

Perhaps not, and perhaps it doesn't matter. I have no way to know.

Well, there is one way... and that is to jump in with both feet.

Will you jump with me?

== Chapter One

I cleared the side, and it was only afterwards that I remembered how far it always is to the surf with the keel rasping on the sand. Too late, now. I let one hand run along the wooden wall, raiding knife held high in the other and knees loose. Just like my mother taught me.

The sea placed a cold green cushion to break my fall, and if he copped a wet, lingering feel while upholding my dignity, what's a little familiarity between old friends? I heard his gurgling laugh tumble onto the beach, and joined in with my harsh cackle.

"Mother, wait!"

"Too late!", I squinted up at the prow, where my long-suffering Lizbet clutched the rail with both hands. I've been hard on youngest daughters over the years, I will admit. "Throw me my satchel, Lizzie."

I pondered if my waistband was dry enough to hold my knife. It wasn't dripping wet, unlike my seat, and that would have to do. "Well?", I asked as I slipped the knife in place.

"Catch!"

I looked up just in time for the satchel to drop into my arms, and for the spray of Lizbet's landing to wash over it and into my face. She came up spluttering, every inch of her thoroughly manhandled by that salty old lecher. This time his chortling was echoed by the rest of the crew above us.

"So you _are_ going to keep your old ma company after all.", I whisper, wiping sand and hair from her brow.

"Keep her out of trouble, more like.", she sniffed, standing tall in her dripping wet cloak with her own, waterlogged satchel bumping at her shins like a lonely puppy.

I cackled, threw our satchels up on the beach, and with my old grabby friend's help, we both pushed the prow off the sand and wished our family and friends a safe trip home. Lizbet and I stood in the surf, the wash softly drawing the sand over our toes and burying our feet, arm in arm until the ship passed out of the little bay and our sight.

I turned to my youngest, and asked:

"Hungry?"
