= Living with Immortality
Mathieu Glachant <syvwlch@gmail.com>
:toc:

== Prologue

This is the bit I'm really bad at.

I was there, I saw it happen, and with enough wine in me, I can tell the story well enough. Enough to make you laugh at our folly, with enough wine in you. Sober, I can whisper the same story to heavy-lidded children fighting against sleep, and mostly they will dream of courage and treasure. Mostly.

So yes, back home I'm a teller of tales... for people I've known their entire lives, and who've heard my tales exactly that long. If I get a little lost, they all know how these stories go, and are not slow to remind me.

You, however... Children of children of strangers, posterity, how shall I address you? What do we share, you and I, which I can build this story on, that we might meet in the middle?

Have you stood in the surf, the sand sweeping over your toes and the foam splashing your shins? Can I start there, and assume you will know that much?

Have you given birth, suckled a child? Have you sailed at night towards the lights of a sleepy port rich for the plunder? Have you buried husbands?

Perhaps not, and perhaps it doesn't matter. I have no way to know.

Well, there is one way... and that is to jump in with both feet.

Will you jump with me?

== Chapter One
