= Return to Paradise
Mathieu Glachant <syvwlch@gmail.com>
Required words: 'hateful genius' & 'menacing light fixture'
:toc:

== 1 "Yea, though I walk ..."
// Establish dramatis personae.

Frankly, I do not give a damn for poor mad Da. Not anymore.

Why does he get to rant & rave, spill tears, throw himself on this hateful ground that drank that bright hot blood with silent, awful relish? Why must I be the one to hold it together, to drag his sorry ass up and forward, to breathe while holding in that awful keening cry trapped between my teeth?

They were my babies too. My bright hot sons shining with the love poured from my breast into their hungry mouths. My own blood keeping me warm thru how many winters? Ha. As if I did not know to the day, to the hour, how long they were mine... and how long they have not been.

No, I do not give a damn for poor mad Da. I'm dragging his ass to the enclave for one reason and one reason only. So we can both stand there, the distraught yet united parents pleading for their sole surviving son. Stand first so we can throw ourselves to our knees and beg for what is ours, deny that it was stolen from us and promise that we will take better care of this gift if only it be granted again.

I will drag mad Da there by his hair if I have to. I will breathe thru clenched teeth until we get there, and I will lie thru them when we do.

For my bright hot sons.

== 2
// Get past gatekeeper and into garden

Finding the way was the easy part.

During the day, the enclave smolders like a dawn that never comes, an ember trapped between the ground and the low, scudding clouds. At night, it shines behind the unending hills, a luminous cloud at the foot of a narrow pour of light decanted from the black sky.

Walking was the hard part but I know how to walk and how to remind mad Da how to walk. One leaden shove at a time.

And so here I stand, and here mad Da sits, both squinting at the walls of the enclave. I should not have stopped walking, because now I will need to pick him up again, but I cannot see a way in. I do not know the way in and my legs quiver beneath me.

A beam of light sweeps towards us, raising the texture of the ground before us, highlighting every bump and hiding every dip, before it blinds us and we cast our eyes down.

"Ye may come inside, an ye wish it." we hear, as the beam sweeps away again. It pours from the hand of he who spoke, as straight as that fall of light in the sky above us, and only now do I feel its brassy heat fade from my face. I do not miss it.

"Aye, lord, an it please ye." I bow to drag mad Da back to his feet.

"Follow ye me." he points his light back at the walls, and we stumble in his shadow, blind to what lies beneath our aching feet.

== 3
// Meet gardener. Must choose to lose knowledge in order to stay.

== 4
// Shed clothing and other trappings of knowledge. Find tree 'menacing light fixture'.

== 5
// Talk Da into choice. See results in him.

== 6
// Choose. Meet serpent 'Hateful genius'. Serpent explains what she lost.

== 7
// Gardener explains what she gained. Takes her to sleeping Da, calling her Eve.


The End
