= Return to Paradise
Mathieu Glachant <syvwlch@gmail.com>
Required words: 'hateful genius' & 'menacing light fixture'
:toc:

== 1 "In the valley of the shadow of death..."
// Establish dramatis personae.

Frankly, I do not give a damn for poor mad Da. Not anymore.

Why does he get to rant & rave, spill tears, throw himself on this hateful ground that drank that bright hot blood with silent, awful relish? Why must I be the one to hold it together, to drag his sorry ass up and forward, to breathe while holding in that awful keening cry trapped between my teeth?

They were my babies too. My bright hot sons shining with the love poured from my breast into their hungry mouths. My own blood keeping me warm thru how many winters? Ha. As if I did not know to the day, to the hour, how long they were mine... and how long they have not been.

No, I do not give a damn for poor mad Da. I'm dragging his ass to the enclave for one reason and one reason only. So we can both stand there, the distraught yet united parents pleading for their sole surviving son. Stand first so we can throw ourselves to our knees and beg for what is ours, deny that it was stolen from us and promise that we will take better care of this gift if only it be granted again.

I will drag mad Da there by his hair if I have to. I will breathe thru clenched teeth until we get there, and I will lie thru them when we do.

For my bright hot sons.

== 2 "Yea, though I walk..."
// Get past gatekeeper and into garden

Finding the way was the easy part.

During the day, the enclave smolders like a dawn that never comes, an ember trapped between the ground and the low, scudding clouds. At night, it shines behind the unending hills, a luminous cloud at the foot of a narrow pour of light decanted from the black sky.

Walking was the hard part but I know how to walk and how to remind mad Da how to walk. One leaden shove at a time.

And so here I stand, and here mad Da sits, both squinting at the walls of the enclave. I should not have stopped walking, because now I will need to pick him up again, but I cannot see a way in. I do not know the way in and my legs quiver beneath me.

A beam of light sweeps towards us, raising the texture of the ground before us, highlighting every bump and hiding every dip, before it blinds us and we cast our eyes down.

"Ye may come inside, an ye wish it." we hear, as the beam sweeps away again. It pours from the hand of he who spoke, as straight as that fall of light in the sky above us, and only now do I feel its brassy heat fade from my face. I do not miss it.

"Aye, guardian, an it please ye." I bow to drag mad Da back to his feet.

"Follow ye me." he points his light back at the walls, and we stumble in his shadow, blind to what lies beneath our aching feet.

== 3 "Thy rod and thy staff..."
// Shed clothing and other trappings of knowledge.

The enclosure looms as we near: a rising wall of white light ahead, inky darkness still behind, in the corner of my eye, and a black cutout where our guide stands waiting, the light spilling around the edges of his form, softening it and threatening to consume it the closer we come.

I do not see the gate as we pass inside, my eyes drowning like someone unable to breathe in a hurricane until they pass the wall of the storm and suddenly all is ominous quiet and nerves.

Inside the enclosure is filled with light. Soft, dense light with the power and time to banish shadow from every crack and hollow, to settle in and own its space. My eyes see, now, possibly for the first time.

Our guide stands to our left, a little taller yet than my Da. He has left his shadow outside, and that terrible beam is revealed to be a small dull thing held loosely in his right hand. He is naked, and unblemished, and I am filled with shame.

Shame that my flesh is rumpled and creased, yes, that it has not held this glow of health and vigor for a long time... but mostly shame for the dirty rags that cloak it. My skin crawls at the thought of the shadow clinging to my limbs, this darkness Da and I have brought here with us.

Our guide smiles as we both peal it from our bodies and cast it to the ground.

"He will meet ye now." the guide murmurs, raising his left arm to point to the heart of the enclosure, where the lightfall is rooted to the earth.

== 4 "My cup runneth over..."
// Meet gardener. Learn that the knowledge of good and evil has no end.

We find him in his garden, surrounded by the fruits of his hands which he most loves. He turns his face to us as we step into the clearing where he has planted that tree which roots the light pouring from the sky, the light we have followed into his presence.

Our knees thud into the soft earth, and we cannot look upon that face.

"Be ye welcome." he says, "Ye come for your son."

"Yea, Lord, we would see both of our sons again, an thee will it."

He sighs, like the wind thru a stand of birch in the first flush of spring.

"I told thee when ye both left that death and grief lay outside these walls. Surely thou, at least, knew they were not your special burden to bear alone."

"Thou did say so, Lord, and I knew the weight of my choice lay upon all those I would bear and love." I cry. "I have plumbed the depth of this knowledge, yea to the very dregs, and I am sick unto death of it."

"Even so, I will not give thy dead son back to thee." he says firmly. "As I will not take thy choice from thee."

"Death has come for one of my sons before it came for me. An it had not, what would I know of grief?" I shout. "Death has not claimed the other! Why can I not hold him in my arms, and together grieve the loss of his brother?"

"This also, ye wish both to know?" he asks.

"Yea, Lord, we both wish to know why our sole remaining son is held from his mother." I wrestle the rage back behind my teeth, and glance aside at poor mad Da. He stares at me, wide-eyed and pale. I know not which of us has scared him more, but I continue. "And from his father."

"Your son is dead by the hand of his brother, who spilled his blood upon the earth."

Oh. Now I know... and yet I knew? Whose is this scream of grief and rage I hear soaring to the sky? Oh I know this too. I know too much. Forgive me I know so much. Forgive me my son. I know the name of your murderer and I cannot hate him. Forgive me my son. I know the name of your crime and I cannot forgive you.

Now I know there is no plumb line of grief long enough to find the bottom of this knowledge, and death is not the fiercest monster to crawl from its depths.

Oh, forgive me.

== 5 "He leadeth me..."
// Must choose to lose knowledge in order to stay.

"Eve, stand." the Lord orders gently, his hand beneath my elbow. I do not know if I can obey. "Adam needs thee."

I stand. I raise my eyes to the Lord's face, no longer afraid to see there something I do not wish to know. He is crying too.

"Thy son, and thy daughters, I cannot free from thy choice. They will know its bitter fruits until the ends of their days on the earth, and there is nothing even I can do to unmake this now." he sighs. "Eve, from thy lips and Adam's I can take this cup."

Poor mad Da I can hear wailing as he rolls in the dirt at our feet. I sob.

"Yea, verily can I take this knowledge from ye both... but it will be for thee and he as if thy choice was never made." He gazes into my eyes, to see if I know what he is asking. "Ye will not know your sons, neither the victim nor the murderer. Ye will not know your daughters, nor the sons and daughters they shall bear upon the earth. Ye will not know their pain and grief, an you choose to not know."

He looks down at our feet, and sighs again.

"I fear thee will need to choose for Adam, one last time."

== 6 "He restoreth my soul..."
// See tree as 'menacing light fixture'. Talk Da into choice. See results in him.

The lord leaves us at the foot of his brightest tree. I hold poor mad Da in my arms, and rock him gently. I shush and we both cry. Slowly he grows quiet and still. I feel him breathe against me, like all the men of my line have before.

Would I ache not to feel this, if I no longer knew it?

"I am so tired, Eve." he murmurs into my neck. "I think I am ready now."

"Yes, my love. I know you are." I caress his brow with my hand, and wipe the tears from his face with my hair. "Be strong now."

He sits up, away from me. It takes some time, but eventually he turns back to me, his cheeks blotchy and his eyes red. His lips are a firm line, and he nods, not trusting his voice. I see in him the earnest boy I first met here, and the man I have loved outside for so many years.

I stand and turn towards the tree behind me.

It soars above me, straight and glossy with just the slightest shimmer like water poured steadily from great height. Only where it meets the ground does it bear fruit, throwing up great arching limbs edged with sparkling orbs in their millions. I have reason to know they fall to hand at the slightest touch, and feel strangely heavy in my palm.

I once thought it beautiful.

Now I know beauty is not its purpose. It is there to shed light, to banish darkness. Like a menacing light fixture hanging above the killing floor of an abbatoir, it makes things known. Things we would perhaps rather not know about what that light enables, about the choices it offers.

I choose a fruit which fits my hand as if made for it, and bring it to Adam. He nods, takes a bite as I hold it for him, and closes his eyes as he swallows.

"Well met madam, my name is Adam." He smiles at me. The lines are not gone from his face, but they fall across it as if someone has taken up the excess skin, bunching at the corner of his eyes and lips. "Have thee seen my Eve? She was here but a moment ago!"

I look up over his shoulder, and I see the Lord standing at the edge of the clearing.

"She waits for thee. See, the Lord will take thee to her." I turn him around, and briefly clutch him to me before giving him a little shove.

He laughs delightedly, and strides eagerly away, wiping the fruit's juice from his breast where I smeared him with it. I hear him babbling excitedly to the Lord as they walk away, but I cannot bear to watch.

== 7 "I will fear no evil..."
// Meet serpent 'Hateful genius'. Serpent explains what she will lose, but she chooses to forget.

"That is an evil thing to have done." a cold voice sounds from above me.

"Yea, we would both know, Lucy." I snap, frowning up at her, coiled in the arching branches of the tree. "Did I not learn to know evil from thee?"

"Knowing evil from me is easy..." she chuckles hoarsely. "It is knowing me from good that many find difficult."

She writhes briefly to free some length and lower her head down to mine. Thousands of fruits fall from the tree, splattering the ground with a brief drumbeat and my limbs with sticky light.

"So the tempter has made his offer, and Adam has ... made his choice." she hisses. "What will be thine?"

"Peace, at long last peace."

"Bah! Thy choice is death. Worse, thy choice is to never have been." She spits. "Thy choice is to abandon thy brood, as he has forsaken them outside his walls."

"I would sooner forget thy promises, bringer of light, but I find I cannot."

"The taste of knowledge not to thy liking?" she taunts. "The brew too strong?"

"Mother of lies!" I rage.

"Ah. It takes a mother to know one, Eve." she whispers. "An thou not listened to my counsel, would Adam and thee have ever known each other? Would ye have known the joy of holding a child in your arms?"

I say nothing, for she speaks the bitter truth, as she always does.

"Yea, Lucifer, I know thy words for the truth, and I choose not to know.", I spit back in her face.

Reaching down, I scrape the drying light from my belly, and watching her bright, hot eyes I lick the innocence from my fingers, hoping that the end will be swift.

== Epilogue - "He maketh me to lie down..."
// Gardener takes her to sleeping Da, whose side is open. She falls asleep as the Lord bends down to kiss her.

Adam lay sleeping, his side open with a little blood pooling on the ground beneath him.

The Lord guided Eve to Adam. She looked a little dazed, but trusting, as she lay down besides the father of her children.

The Lord brushed the hair from her face, and she closed her eyes as he bent down to put his lips to her lips, the knife ready in his hand.

THE END
