= Return to Paradise
Mathieu Glachant <syvwlch@gmail.com>
:toc:

== 1 "In the valley of the shadow of death..."

I do not give a damn for poor mad Da.

Why should I be the one to continue to breathe? To hold that awful keening cry behind my teeth? They were my babies too, bright with hot love poured from my heart into their hungry mouths.

How dare he spill his tears upon this hateful ground? Did it no drink its fill of bright hot blood? Have we not fed it the limbs of our dead son, and yet it stays mute on the fate of his brother?

No, I do not give a damn for poor mad Da.

I will drag him there with me, so we can stand united, the distraught parents pleading for their sole surviving son. Stand so we can fall to our knees and promise that we will take better care of this gift, if its thieves grant it anew.

I will drag mad Da there by his hair if I have to. I will breathe thru clenched teeth until we get there, and I will lie thru them when we do.

For my bright hot sons.

== 2 "Yea, though I walk..."

Finding the way is easy. The enclave smolders like a dawn that never comes, an ember trapped between the low, scudding clouds and the unending hills.

It is the sight from the crest of each hill we climb that is hard, the tumble into another dark valley to find the foot of the next hill crowned in light, and then another climb, and another, until suddenly here I stand, and here mad Da sits, squinting down and blinking.

A thin bright ribbon pours from the dark sky and throws up thick, roiling coils of luminous light which overspill the unbroken rim of the white walls to throw shadows across this last valley.

I do not know the way in and my legs quiver beneath me, but ere I fall a beam of light sweeps towards us, highlighting every bump and hiding every dip, before it blinds us and we cast our eyes down.

"Ye may come inside, if ye wish it." the guardian has come to meet us. His light sweeps away again, streaming from his hand straight as that ribbon above, and only now do I feel its brassy heat fade from my face.

"If it please ye, guardian." I bow down and drag mad Da back to his feet.

"Follow ye me." he points his light back at the walls, and we stumble in his shadow, blind to what lies beneath our aching feet.

== 3 "Thy rod and thy staff..."

The walls loom ahead as we near, rising like a wave of light about to break. I squint ahead, the light spilling around the edges of our guide, threatening to consume him before crashing down upon our heads.

I do not see a gate as we pass inside, my eyes drowning like someone unable to breathe in a hurricane until they pass the wall of the storm and suddenly all is ominous quiet and nerves.

Inside, the light is full and dense, with the power and time to banish shadow wherever it may hide. My eyes see, they cannot not see.

Our guide stands to our left, a little taller yet than my Da. He is naked, and unblemished, and I am filled with shame. Shame that my flesh is rumpled and creased, yes, that it has not held this glow of health and vigor for a long time... but mostly shame for the dirty rags that cloak it.

My skin crawls at the thought of the shadow clinging to my limbs, this darkness Da and I have brought here with us. Our guide smiles as we both peel it from our limbs.

"He will see ye now." the guide murmurs, raising his left arm to point to the heart of the enclosure, where the lightfall is rooted to the earth.

== 4 "My cup runneth over..."

We find Him surrounded by the fruit of His hands, where He has planted the light falling from the sky, the light we have followed into His presence.

He turns His face to us and our knees thud into the soft earth. We cannot look upon that face.

"Be ye welcome." He says, "Ye come for your son."

"Verily, Lord, we would see _both_ of our sons again, if Thee will it."

He sighs, like the wind thru a stand of birch in the first flush of spring.

"I told thee when ye both left that death and grief lay outside these walls. Surely thou, at least, knew they were not your burdens to bear alone."

"Thou didst say so, Lord, and I knew those I would bear would also feel their weight." I cry. "I have plumbed the depth of this knowledge, yea to the very dregs, and I am sick unto death of it."

"Even so, I will not give thy dead son back to thee." he says firmly. "As I will not take thy choice from thee."

"Death has come for one of my sons before it came for me. if it had not, what would I know of grief?" I shout. "Death has not claimed the other! Why can I not hold him in my arms, and together grieve the loss of his brother?"

"This also, ye wish _both_ to know?"

"Yea, Lord, we wish to know why our sole remaining son is held from his mother." I wrestle the rage to glance aside at poor mad Da. He stares at me, wide-eyed and pale. I know not which of us has scared him more, but I continue. "And from his father."

"Your son is dead by the hand of his brother, who spilled his blood upon the earth."

Oh. Now I know... and yet I knew?

Whose is this scream of grief and rage I hear soaring to the sky? Oh I know this too.

I know too much.

Forgive me I know so much. Forgive me my son. I know the name of your murderer and I cannot hate him. Forgive me my son. I know the name of your crime and I cannot forgive you.

Now I know there is no line of grief long enough to plumb this knowledge, and death is not the fiercest monster to crawl from its depths.

Oh, forgive me.

== 5 "He leadeth me..."

"Eve, stand." He orders gently, His hand beneath my elbow. I do not know if I can obey. "Adam needs thee."

I stand. I raise my eyes to His face, no longer afraid to see there something I do not wish to know. He is crying too.

"Thy son, and thy daughters, I cannot free from thy choice. They will know its bitter fruits until the ends of their days. There is nothing even I can do to unmake this now." He sighs. "Eve, from thy lips and Adam's I can take this cup."

Poor mad Da I can hear wailing as he rolls in the dirt at our feet. I sob.

"Yea, I can take this knowledge from ye both... but it will be for thee and he as if thy choice was never made." He gazes into my eyes, to see if I know what he is asking. "Ye will not know your sons, neither the victim nor the murderer. Ye will not know your daughters, nor the sons and daughters they shall bear in turn. This can I do, if ye both choose to not know."

He looks down at our feet, and sighs again.

"I fear thou wilst need to choose for Adam, one last time."

== 6 "He restoreth my soul..."

The lord leaves us at the foot of his brightest tree. I rock poor mad Da in my arms gently. I shush and we cry. Slowly I feel him grow still against me, like all the men of my line have before.

"I am so tired, Eve." he murmurs into my neck. "I think I am ready now."

"Yes, my love. I know thou art." I wipe the tears from his face with my hair. "Be strong now."

He sits up, away from me. After some time, he turns to face me, cheeks blotchy but lips firm. I see in him the earnest boy I first met here, and the man I have loved since.

He nods, not trusting his voice. I stand and turn towards the tree behind me.

It soars above us, straight and glossy with just the slightest shimmer of water poured steadily from a great height. Only where it meets the ground does it bear fruit, throwing up great arching limbs edged with sparkling orbs in their millions. I have reason to know they fall to hand at the slightest touch,  strangely heavy and cold.

I once thought the tree beautiful. Now I know that its purpose is to shed light, like a *menacing light fixture* hanging above the killing floor of an abattoir. It makes our choices known to us, and the fruits those choices bear.

One more time, I choose a fruit which fits my hand as if made for it, and bring it to Adam. He nods, takes a bite as I hold it for him, and closes his eyes as he swallows.

"My name is Adam." He smiles at me. The lines are not gone from his face, but they fall across it as if someone has taken up the excess skin, bunching at the corner of his eyes and lips. "Hast thou seen my Eve? She was here but a moment ago!"

"She waits for thee. See, the Lord will take thee to her." I turn him around, and briefly clutch him to me before giving him a little shove towards the Lord at the edge of the clearing.

He laughs delightedly, and strides eagerly away, wiping the fruit smeared on his breast. I hear him babbling excitedly as they walk away, but I cannot bear to watch.

== 7 "I will fear no evil..."

"That is an evil thing to have done." a cold voice sounds from above me.

"Yea, we would both know, bringer of light." I snap, frowning up at her, coiled in the arching branches of the tree. "Did I not know evil from thee?"

"Knowing evil from me is easy..." she chuckles. "The trick is knowing me from good."

She writhes briefly to free some length and lower her head down to mine. Thousands of fruits fall from the tree, splattering the ground with a brief drumbeat and my limbs with sticky light.

"So the tempter has made his offer, and Adam has ... made his choice." she hisses. "What will thine be?"

"Peace, at long last peace."

"Bah! Thy choice is death. Worse, thy choice is to never have been." She spits. "Thou choosest to forget thy brood, as he has forsaken them."

"I would sooner forget thy promises, mother of lies, as perhaps thou hast."

"Ah. It takes a mother to know one, Eve." she whispers. "But my counsel, wouldst thou have truly known Adam? Wouldst thou have known the joys and pains of motherhood?"

Damn her. She, the *hateful genius* of this place of unsparing light, has never needed to lie to me.

"Yea, Lucifer, I know thy words for the truth, and I choose not to know them anymore."

I lick the sticky innocence from my fingers, hoping that the end will be swift, and the last I see are her eyes on mine.

== Epilogue - "He maketh me to lie down..."

Adam and Eve lay together.

Him with his eyes closed, and his side open with a little blood pooling beneath.

Her with her eyes open staring up at the face of the Lord, as He bent down to put His lips to her lips, the knife ready in His hand.

THE END
