= Return to Paradise
Mathieu Glachant <syvwlch@gmail.com>
Required words: 'hateful genius'
:toc:

== 1 "In the valley of the shadow of death..."

I do not give a damn for poor mad Da. Not anymore.

Why does he get to spill his tears on this hateful ground that drank that bright hot blood with equal relish? Why must I continue to breathe while holding that awful keening cry behind my teeth and drag us both forward?

They were my babies too, brights with love poured hot from my breast into their hungry mouths. My own blood keeping me warm thru how many winters? Ha. As if I did not know to the day, to the hour, how long they were mine... and how long they have not been.

No, I do not give a damn for poor mad Da. I'm dragging his ass to the enclave for one reason and one reason only. So we can both stand there, the distraught yet united parents pleading for their sole surviving son.

Stand first so we can throw ourselves to our knees and beg for what is ours, deny that it was stolen from us and promise that we will take better care of this gift if only it be granted again.

I will drag mad Da there by his hair if I have to. I will breathe thru clenched teeth until we get there, and I will lie thru them when we do.

For my bright hot sons.

== 2 "Yea, though I walk..."

Finding the way is easy. The enclave smolders like a dawn that never comes, an ember trapped between the low, scudding clouds and the unending hills. Each one we climb crowned with a luminous cloud at the foot of a narrow pour of light decanted from the black sky.

It is the sight from every crest that is hard. The tumble into another dark valley, shoving poor mad Da for fear he will never get up again.

Until suddenly here I stand, and here mad Da sits, both gaping at the walls of the enclave awash in light below us. I cannot see a way in. I do not know the way in and my legs quiver beneath me.

A beam of light sweeps towards us, raising the texture of the ground before us, highlighting every bump and hiding every dip, before it blinds us and we cast our eyes down.

"Ye may come inside, an ye wish it." we hear, as the beam sweeps away again. It pours from the hand of he who spoke, as straight as that fall of light in the sky above us, and only now do I feel its brassy heat fade from my face.

"An it please ye, guardian." I bow to drag mad Da back to his feet.

"Follow ye me." he points his light back at the walls, and we stumble in his shadow, blind to what lies beneath our aching feet.

== 3 "Thy rod and thy staff..."

The wall looms ahead as we near, rising like a wave of light about to break. I squint ahead to our guide, the light spilling around the edges of his form,  threatening to consume it before crashing down upon our heads.

I do not see the gate as we pass inside, my eyes drowning like someone unable to breathe in a hurricane until they pass the wall of the storm and suddenly all is ominous quiet and nerves.

Inside, the light is soft and dense. It has the power and time to banish shadow from every crack and hollow. My eyes see, now, possibly for the first time.

Our guide stands to our left, a little taller yet than my Da. He is naked, and unblemished, and I am filled with shame. Shame that my flesh is rumpled and creased, yes, that it has not held this glow of health and vigor for a long time... but mostly shame for the dirty rags that cloak it.

My skin crawls at the thought of the shadow clinging to my limbs, this darkness Da and I have brought here with us. Our guide smiles as we both peal it from our bodies and cast it to the ground.

"He will see ye now." the guide murmurs, raising his left arm to point to the heart of the enclosure, where the lightfall is rooted to the earth.

== 4 "My cup runneth over..."

We find him surrounded by the fruit of his hands. He turns his face to us as we step into the clearing where he has planted that tree which roots the light pouring from the sky, the light we have followed into his presence.

Our knees thud into the soft earth, and we cannot look upon that face.

"Be ye welcome." he says, "Ye come for your son."

"Yea, Lord, we would see both of our sons again, an thee will it."

He sighs, like the wind thru a stand of birch in the first flush of spring.

"I told thee when ye both left that death and grief lay outside these walls. Surely thou, at least, knew they were not your special burden to bear alone."

"Thou didst say so, Lord, and I knew the weight of my choice lay upon all those I would bear and love." I cry. "I have plumbed the depth of this knowledge, yea to the very dregs, and I am sick unto death of it."

"Even so, I will not give thy dead son back to thee." he says firmly. "As I will not take thy choice from thee."

"Death has come for one of my sons before it came for me. An it had not, what would I know of grief?" I shout. "Death has not claimed the other! Why can I not hold him in my arms, and together grieve the loss of his brother?"

"This also, ye wish both to know?" he asks.

"Yea, Lord, we both wish to know why our sole remaining son is held from his mother." I wrestle the rage back behind my teeth, and glance aside at poor mad Da. He stares at me, wide-eyed and pale. I know not which of us has scared him more, but I continue. "And from his father."

"Your son is dead by the hand of his brother, who spilled his blood upon the earth."

Oh. Now I know... and yet I knew? Whose is this scream of grief and rage I hear soaring to the sky? Oh I know this too. I know too much. Forgive me I know so much. Forgive me my son. I know the name of your murderer and I cannot hate him. Forgive me my son. I know the name of your crime and I cannot forgive you.

Now I know there is no plumb line of grief long enough to find the bottom of this knowledge, and death is not the fiercest monster to crawl from its depths.

Oh, forgive me.

== 5 "He leadeth me..."

"Eve, stand." the Lord orders gently, his hand beneath my elbow. I do not know if I can obey. "Adam needs thee."

I stand. I raise my eyes to the Lord's face, no longer afraid to see there something I do not wish to know. He is crying too.

"Thy son, and thy daughters, I cannot free from thy choice. They will know its bitter fruits until the ends of their days. There is nothing even I can do to unmake this now." he sighs. "Eve, from thy lips and Adam's I can take this cup."

Poor mad Da I can hear wailing as he rolls in the dirt at our feet. I sob.

"Yea, verily can I take this knowledge from ye both... but it will be for thee and he as if thy choice was never made." He gazes into my eyes, to see if I know what he is asking. "Ye will not know your sons, neither the victim nor the murderer. Ye will not know your daughters, nor the sons and daughters they shall bear upon the earth. Ye will not know their pain and grief, an ye both choose to not know."

He looks down at our feet, and sighs again.

"I fear thou wilst need to choose for Adam, one last time."

== 6 "He restoreth my soul..."

The lord leaves us at the foot of his brightest tree. I hold poor mad Da in my arms, and rock him gently. I shush and we both cry. Slowly I feel him grow still against me, like all the men of my line have before.

"I am so tired, Eve." he murmurs into my neck. "I think I am ready now."

"Yes, my love. I know thou art." I wipe the tears from his face with my hair. "Be strong now."

He sits up, away from me. It takes some time, but eventually he turns back to me. His cheeks are blotchy but his lips are firm. He nods, not trusting his voice. I see in him the earnest boy I first met here, and the man I have loved outside for so many years.

I stand and turn towards the tree behind me.

It soars above me, straight and glossy with just the slightest shimmer like water poured steadily from a great height. Only where it meets the ground does it bear fruit, throwing up great arching limbs edged with sparkling orbs in their millions. I have reason to know they fall to hand at the slightest touch,  strangely heavy and cold.

I once thought the tree beautiful. Now I know that its purpose is to shed light, like a _menacing light fixture_ hanging above the killing floor of an abattoir. It allows certain choices to be made and once made, it makes their fruits known.

One more time, I choose a fruit which fits my hand as if made for it, and bring it to Adam. He nods, takes a bite as I hold it for him, and closes his eyes as he swallows.

"My name is Adam." He smiles at me. The lines are not gone from his face, but they fall across it as if someone has taken up the excess skin, bunching at the corner of his eyes and lips. "Hast thou seen my Eve? She was here but a moment ago!"

I look up over his shoulder, and I see the Lord standing at the edge of the clearing.

"She waits for thee. See, the Lord will take thee to her." I turn him around, and briefly clutch him to me before giving him a little shove.

He laughs delightedly, and strides eagerly away, wiping the fruit's juice from his breast where I smeared him with it. I hear him babbling excitedly to the Lord as they walk away, but I cannot bear to watch.

== 7 "I will fear no evil..."

"That is an evil thing to have done." a cold voice sounds from above me.

"Yea, we would both know, bringer of light." I snap, frowning up at her, coiled in the arching branches of the tree. "Did I not learn to know evil from thee?"

"Knowing evil from me is easy..." she chuckles hoarsely. "The trick is knowing me from good."

She writhes briefly to free some length and lower her head down to mine. Thousands of fruits fall from the tree, splattering the ground with a brief drumbeat and my limbs with sticky light.

"So the tempter has made his offer, and Adam has ... made his choice." she hisses. "What will thine be?"

"Peace, at long last peace."

"Bah! Thy choice is death. Worse, thy choice is to never have been." She spits. "Thou choosest to forget thy brood, as he has forsaken them."

"I would sooner forget thy promises, mother of lies, as perhaps thou hast."

"Ah. It takes a mother to know one, Eve." she whispers. "An thou not listened to my counsel, wouldst thou have truly known Adam? Wouldst thou have known the joys and pains of motherhood?"

Damn her. She, the hateful genius of light, has never needed to lie to me.

"Yea, Lucifer, I know thy words for the truth, and I choose not to know."

I scrape the drying light from my limbs, and watching her bright, hot eyes I lick the innocence from my fingers, hoping that the end will be swift.

== Epilogue - "He maketh me to lie down..."

Adam and Eve lay on the grass.

Him with his eyes closed, and his side open with a little blood pooling beneath him. Her with her eyes open staring up at the face of the Lord, as he bent down to put his lips to her lips, the knife ready in his hand.

THE END
